version: "3.9"

services:
  mf-root-config:
    build:
      context: .  # Current directory (mf-root-config)
    ports:
      - "9000:9000"
    volumes:
      - .:/app  # Map mf-root-config to /app
      - /app/node_modules
    command: yarn start
    environment:
      - NODE_ENV=development

  mf-navbar:
    build:
      context: ../mf-navbar  
    ports:
      - "9001:9001"
    volumes:
      - ../mf-navbar:/app
      - /app/node_modules
    command: yarn start
    environment:
      - NODE_ENV=development

  mf-employees:
    build:
      context: ../mf-employees  
    ports:
      - "9002:9002"
    volumes:
      - ../mf-employees:/app
      - /app/node_modules
    command: yarn start
    environment:
      - NODE_ENV=development

  mf-employee-details:
      build:
        context: ../mf-employee-details  
      ports:
        - "4200:4200"
      volumes:
        - ../mf-employee-details:/app
        - /app/node_modules
      command: yarn start
      environment:
        - NODE_ENV=development
