version: "3.9"

services:
  mf-root-config:
    build:
      context: .  # Local directory
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start
    environment:
      - NODE_ENV=development

  mf-navbar:
    build:
      context: https://github.com/hi-malay/mf-navbar.git
    ports:
      - "9001:9001"
    volumes:
      - /app:/app
      - /app/node_modules
    command: yarn start
    environment:
      - NODE_ENV=development

  mf-employees:
    build:
      context: https://github.com/hi-malay/mf-employees.git
    ports:
      - "9002:9002"
    volumes:
      - /app:/app
      - /app/node_modules
    command: yarn start
    environment:
      - NODE_ENV=development

  mf-employee-details:
    build:
      context: https://github.com/hi-malay/mf-employee-details.git
    ports:
      - "4200:4200"
    volumes:
      - /app:/app
      - /app/node_modules
    command: yarn start
    environment:
      - NODE_ENV=development
